services:
  backend:
    container_name: spotify-app-backend-dev
    build: ../backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ../backend/.env
    depends_on:
      - mongo
    volumes:
      - ../backend:/app
      - /app/node_modules
      - ../certs/lyra:/var/www/certs/lyra:ro
 
  frontend:
    container_name: spotify-app-frontend-dev
    build: ../frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules

  mongo:
    image: mongo:8.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
