services:
  backend:
    container_name: spotify-app-backend
    build: ../backend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    env_file:
      - ../backend/.env
    depends_on:
      - mongo
    volumes:
      - ../frontend/dist:/app/dist
      - /var/www/certs:/var/www/certs:ro

  mongo:
    image: mongo:8.0
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
